    -- Optional: seed the current menu into Supabase after schema.sql.
    insert into public.menu_items (id, category, name, description, price, popular, available) values
    ('m1', 'fresh-fish', 'Grilled Hammour Fillet', 'Whole hammour fillet, chargrilled with lemon and herbs.', 68, true, true),
    ('m2', 'fresh-fish', 'Pan-Seared Salmon', 'Norwegian salmon, crisp skin, brown butter and dill.', 72, false, true),
    ('m3', 'fresh-fish', 'Steamed Sea Bass', 'Whole sea bass steamed with ginger, soy and scallion.', 65, false, true),
    ('m4', 'prawns', 'Garlic Butter Prawns', 'Jumbo prawns, roasted garlic butter, chilli flake.', 58, true, true),
    ('m5', 'prawns', 'Prawn Masala', 'Prawns simmered in a spiced tomato-onion masala.', 55, false, true),
    ('m6', 'prawns', 'Chilli Prawns', 'Wok-tossed prawns, dried chilli, spring onion.', 60, false, true),
    ('m7', 'crab', 'Whole Chilli Crab', 'Whole mud crab in a sweet-spicy chilli sauce.', 145, true, true),
    ('m8', 'crab', 'Crab Curry', 'Crab claws in a coconut and curry-leaf gravy.', 95, false, true),
    ('m9', 'crab', 'Butter Garlic Crab', 'Whole crab, roasted garlic butter, cracked pepper.', 130, false, false),
    ('m10', 'lobster', 'Grilled Half Lobster', 'Half lobster, char-grilled, garlic herb butter.', 165, true, true),
    ('m11', 'lobster', 'Lobster Thermidor', 'Lobster in a creamy mustard-cheese gratin.', 190, false, true),
    ('m12', 'lobster', 'Lobster Bisque Roll', 'Buttered roll filled with lobster bisque salad.', 85, false, true),
    ('m13', 'squid', 'Crispy Fried Calamari', 'Lightly battered calamari rings, lemon aioli.', 45, true, true),
    ('m14', 'squid', 'Squid Sambal', 'Squid tossed in a smoky sambal chilli paste.', 50, false, true),
    ('m15', 'squid', 'Grilled Squid Skewers', 'Char-grilled squid skewers, lime and chilli oil.', 55, false, true),
    ('m16', 'grilled', 'Mixed Seafood Grill Platter', 'Fish, prawn, squid and lobster off the grill.', 175, true, true),
    ('m17', 'grilled', 'Grilled King Fish', 'King fish steak, charred, tamarind glaze.', 70, false, true),
    ('m18', 'grilled', 'Grilled Prawn Skewers', 'Skewered prawns, smoked paprika butter.', 62, false, true),
    ('m19', 'fried', 'Fish and Chips', 'Beer-battered fish, hand-cut chips, tartare.', 48, false, true),
    ('m20', 'fried', 'Fried Fish Fingers', 'Crumbed fish fingers, house cocktail sauce.', 40, false, true),
    ('m21', 'fried', 'Crispy Fried Prawns', 'Panko-crusted prawns, sweet chilli dip.', 52, false, true),
    ('m22', 'seafood-rice', 'Seafood Fried Rice', 'Wok-fried rice with prawn, squid and fish cake.', 46, true, true),
    ('m23', 'seafood-rice', 'Seafood Paella-Style Rice', 'Saffron rice, mussels, prawn and calamari.', 58, false, true),
    ('m24', 'seafood-rice', 'Crab Fried Rice', 'Fried rice folded through with fresh crab meat.', 60, false, true),
    ('m25', 'biriyani', 'Prawn Biriyani', 'Layered basmati biriyani with spiced prawn.', 52, true, true),
    ('m26', 'biriyani', 'Fish Biriyani', 'Fragrant biriyani rice with marinated fish.', 50, false, true),
    ('m27', 'biriyani', 'Mixed Seafood Biriyani', 'Prawn, fish and squid layered biriyani.', 65, false, true),
    ('m28', 'soups', 'Seafood Chowder', 'Creamy chowder with prawn, fish and corn.', 38, false, true),
    ('m29', 'soups', 'Hot and Sour Prawn Soup', 'Tamarind broth, prawn, lemongrass, chilli.', 35, false, true),
    ('m30', 'soups', 'Crab and Corn Soup', 'Silken crab and sweetcorn soup, egg ribbons.', 36, false, true),
    ('m31', 'starters', 'Seafood Spring Rolls', 'Crisp rolls filled with prawn and glass noodle.', 32, false, true),
    ('m32', 'starters', 'Fish Cutlets', 'Pan-fried fish and potato cutlets, mint chutney.', 30, false, true),
    ('m33', 'starters', 'Prawn Tempura', 'Light tempura prawns, soy-ginger dip.', 42, false, true),
    ('m34', 'main-course', 'Fish Curry with Rice', 'Coconut fish curry, steamed rice, pickle.', 55, false, true),
    ('m35', 'main-course', 'Butter Garlic Lobster Pasta', 'Linguine tossed with lobster and garlic butter.', 78, true, true),
    ('m36', 'main-course', 'Grilled Fish Steak & Vegetables', 'Market fish steak, seasonal roasted vegetables.', 68, false, true),
    ('m37', 'drinks', 'Fresh Lime Mint', 'Lime, mint and soda over ice.', 18, false, true),
    ('m38', 'drinks', 'Mango Lassi', 'Churned yoghurt and mango.', 20, false, true),
    ('m39', 'drinks', 'Iced Karak Tea', 'Spiced milk tea, chilled.', 15, false, true),
    ('m40', 'desserts', 'Baked Cheesecake', 'Vanilla bean cheesecake, berry compote.', 28, false, true),
    ('m41', 'desserts', 'Umm Ali', 'Warm bread pudding, cream, toasted nuts.', 26, true, true),
    ('m42', 'desserts', 'Chocolate Lava Cake', 'Molten centre, vanilla ice cream.', 30, false, true)
    on conflict (id) do update set category=excluded.category, name=excluded.name, description=excluded.description, price=excluded.price, popular=excluded.popular, available=excluded.available;
